//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int Article_id { get; set; }
        public Nullable<int> id { get; set; }
        public string ArticleName { get; set; }
    
        public virtual Book Book { get; set; }
    }
}
