//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop.Models
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class SchemaEntities : DbContext
    {
        public SchemaEntities()
            : base("name=SchemaEntities")
        {
            Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ArticleName> ArticleNames { get; set; }
        public virtual DbSet<Book> Books { get; set; }
    }
}
